# Generated by Django 5.2.1 on 2025-05-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='email',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='phone',
        ),
    ]
