# Generated by Django 5.2.1 on 2025-05-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_testattempt_email_remove_testattempt_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=20),
        ),
    ]
