# Generated by Django 5.2.1 on 2025-05-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='rating',
            field=models.FloatField(default=4.8),
        ),
    ]
