# Generated by Django 5.2.1 on 2025-05-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_certification_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='bio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='certification',
            name='duration',
            field=models.CharField(default='', max_length=50),
        ),
    ]
