# Generated by Django 5.2.1 on 2025-05-22 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_certification_bio_alter_certification_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='rating',
            field=models.FloatField(default=4.8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
