# Generated by Django 5.2.1 on 2025-05-22 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_certification_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='poster',
            field=models.ImageField(max_length=500, upload_to='images/poster'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pfp', models.ImageField(max_length=500, upload_to='images/reviewspfp')),
                ('rating', models.FloatField()),
                ('review', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Certification', to='core.certification')),
            ],
        ),
    ]
