# Generated by Django 5.2.1 on 2025-05-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_gallery_uploaded_at_gallery_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
    ]
