# Generated by Django 5.2.1 on 2025-05-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_video_gallery_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
