# Generated by Django 5.2.1 on 2025-06-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_certificate_certid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=2058)),
                ('category', models.CharField(max_length=100)),
                ('poster', models.ImageField(max_length=500, upload_to='images/blogPoster')),
                ('content', models.TextField()),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
