# Generated by Django 5.2.1 on 2025-06-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='length',
            field=models.IntegerField(default=5),
        ),
    ]
