# Generated by Django 5.2.1 on 2025-06-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_blog_isfeatures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
