# Generated by Django 5.2.1 on 2025-06-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_crated_at_blog_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='isFeatures',
            new_name='isFeatured',
        ),
    ]
