# Generated by Django 5.2.1 on 2025-06-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='topic',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
