# Generated by Django 5.2.1 on 2025-06-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_saveinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='image_zip',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='zipped_images/'),
        ),
    ]
