# Generated by Django 5.2.1 on 2025-06-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_certification_content_certification_image_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestions',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testquestions',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
